Vagrant.configure("2") do |config|
   config.vm.define "ansible1" do |ansible1|
      ansible1.vm.box = "hashicorp/bionic64"
      ansible1.vm.network  "public_network", ip: "192.168.30.20"
   end
   config.vm.define "ansible2" do |ansible2|
      ansible2.vm.box = "hashicorp/bionic64"
      ansible2.vm.network  "public_network", ip: "192.168.30.21"
   end
end


